version: "3.5"

services:
  bot:
    image: c0mputern1k/mfbot-terminal:5.4.0.1
    deploy:
      resources:
          limits:
            cpus: '0.5'
            memory: 2048M
      restart_policy:
        condition: any
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    networks:
      - web

networks:
  web:
    external: true

